// leave off @2x/@3x
const images = {
  logo: require('../Images/logo.png'),
  forward_icon: require('../Images/icons/forward.png'),
  progress_name: require('../Images/icons/progress_name.png'),
  progress_number: require('../Images/icons/progress_number.png'),
  progress_photo: require('../Images/icons/progress_photo.png'),
  progress_pronouns: require('../Images/icons/progress_pronouns.png'),
  progress_ready: require('../Images/icons/progress_ready.png'),
  progress_status: require('../Images/icons/progress_status.png'),
  progress_addfriends: require('../Images/icons/progress_addfriends.png'),
  progress_confirmation: require('../Images/icons/progress_confirmation.png'),
  progress_interests: require('../Images/icons/progress_interests.png'),
  progress_location: require('../Images/icons/progress_location.png'),
  photo_select: require('../Images/icons/photo_select.png'),
  choose_photo_icon: require('../Images/icons/choose_photo_icon.png'),
  library: require('../Images/icons/library.png'),

  barbara: require('../Images/Profiles/barbara.jpg'),
  harold: require('../Images/Profiles/harold.jpg'),
  james: require('../Images/Profiles/james.jpg'),
  linda: require('../Images/Profiles/linda.jpg'),
  john: require('../Images/Profiles/john.jpg'),
  liz: require('../Images/Profiles/liz.jpg'),
  mary: require('../Images/Profiles/mary.jpg'),
  robert: require('../Images/Profiles/robert.jpg'),
  cat: require('../Images/Profiles/cat.jpg'),

  settings: require('../Images/settings.png'), 
  profile: require('../Images/profile_unselected.png'), 
  profileselected: require('../Images/profile_selected.png'), 
  chat: require('../Images/chat_unselected.png'), 
  chatselected: require('../Images/chat_selected.png'), 
  connections: require('../Images/connection_unselected.png'), 
  connectionsselected: require('../Images/connection_selected.png'), 
  home: require('../Images/home_unselected.png'), 
  homeselected: require('../Images/home_selected.png'), 
  available: require('../Images/available.png'), 
  onhold: require('../Images/onhold.png'), 
  open: require('../Images/open.png'), 
  kara: require('../Images/kara.jpg'), 
  eden: require('../Images/eden.jpg'), 
  marie: require('../Images/marie.jpg'), 
  map: require('../Images/map_icon.png'), 
  feed: require('../Images/feed_icon.png'), 
  wilder: require('../Images/wilder.jpg'),
  christian: require('../Images/christian.jpg'),
  cal: require('../Images/cal.jpg'),
}

export default images
